services:
  aitalkmaster:
    build:
      context: ../
      dockerfile: docker-hosting/aitalkmaster.Dockerfile
    container_name: aitalkmaster
    ports:
      - "7000:6000"
    networks:
      - streaming-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../volumes/generated-audio:/app/generated-audio
      - ../volumes/aitalkmaster-logs:/app/logs
      - ../openai_key.txt:/app/openai_key.txt:ro
      - ../aitalkmaster-server/configs/docker-openai-noAudio.yml:/app/config.yml:ro
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6000/statusAitalkmaster"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  
  
networks:
  streaming-network:
    driver: bridge