version: '3.8'

services:
  # Configuration tester service
  config-tester:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: config-tester
    network_mode: "host"  # Use host network to access local services
    volumes:
      - ./test_results:/app/test_results
      - ./generated-audio:/app/generated-audio
      - ./openai_key.txt:/app/openai_key.txt:ro
    environment:
      - OPENAI_API_KEY_FILE=/app/openai_key.txt
      - OLLAMA_CHAT_URL=http://localhost:11434
      - KOKORO_AUDIO_URL=http://localhost:8880/v1
    command: python run_config_tests.py
    restart: "no"
