version: '3.8'

services:
  kokoro:
    image: ghcr.io/remsky/kokoro-fastapi-cpu:latest
    container_name: kokoro
    ports:
      - "8880:8880"
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
      # Optional: Mount a volume for persistent data if needed
      - kokoro_data:/app/data
    networks:
      - kokoro_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8880/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  kokoro_data:
    driver: local

networks:
  kokoro_network:
    driver: bridge
