# Server Configuration
server:
  host: "0.0.0.0"
  port: 6000
  log_file: "./logs/logfile.txt"
  llm_log_file: "./logs/llm_logfile.txt"
  usage:
    use_rate_limit: true
    rate_limit_xForwardedFor: false
    rate_limit_per_day: 100000

# OpenAI Configuration
chat_client:
  mode: "openai"
  key_file: "openai_key.txt"
  default_model: "gpt-4o-mini"
  allowed_models: ["gpt-4o", "gpt-4o-mini", "gpt-3.5-turbo"]


# Aitalkmaster Configuration
aitalkmaster:
  join_key_keep_alive_list: []