# Server Configuration
server:
  host: "0.0.0.0"
  port: 6000
  log_file: "./logs/logfile.txt"
  usage:
    use_rate_limit: true
    rate_limit_xForwardedFor: false
    rate_limit_per_day: 100000
    audio_cost_per_second: 100

# OpenAI Configuration
chat_client:
  mode: "openai"
  key_file: "openai_key.txt"
  default_model: "gpt-4o-mini"
  allowed_models: ["gpt-4o", "gpt-4o-mini", "gpt-3.5-turbo"]

# OpenAI Configuration
audio_client:
  mode: "openai" # "openai" or "kokoro"
  key_file: "openai_key.txt"
  default_voice: "alloy"
  default_model: "tts-1"
  allowed_voices: ["alloy", "ash", "ballad", "coral", "echo", "fable", "onyx", "nova", "sage", "shimmer", "verse"]
  allowed_models: ["tts-1", "tts-1-hd", "gpt-4o-mini-tts"]

liquidsoap_client:
  host: "liquidsoap"
  telnet_port: 1234

icecast_client:
  host: "icecast"
  port: 8000
  admin_password: "password"
  stream_endpoint_prefix: "http://hg.hypergrid.net:7010/stream/" # This variable will only be shown in the /ait/startConversation response to inform the user where to listen to for audio. Remove this variable when not using audio.


# Aitalkmaster Configuration
aitalkmaster:
  join_key_keep_alive_list: []